const styles = {
    home: {
      minHeight: '100vh',
      fontFamily: "'Poppins', sans-serif",
      display: 'flex',
      backgroundColor: '#3a5ba0',
      color: 'white',
    },
    sidebar: {
      width: '20%',
      backgroundColor: '#ffffff',
      padding: '2vw 1vw',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
    },
    sidebarLink: {
      color: '#3a5ba0',
      fontSize: '1.5vw',
      fontWeight: 'bold',
      cursor: 'pointer',
      marginBottom: '2vw',
      position: 'relative',
    },
    sidebarLinkText: {
      display: 'flex',
      alignItems: 'center',
    },
    caretIcon: {
      marginRight: '0.5vw',
    },
    rightCaret: {
      marginRight: '0.5vw',
    },
    termList: {
      marginTop: '1vw',
      paddingLeft: '1.8vw', // Ensure the terms are aligned under the "활동" text
    },
    termItem: {
      color: '#3a5ba0',
      fontSize: '1.2vw',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      padding: '0.5vw 0',
    },
    content: {
      width: '80%',
      padding: '2vw',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
      banner: {
        backgroundColor: '#ffffff',
        borderRadius: '1vw',
        padding: '2vw',
        boxShadow: '0 0.5vw 1vw rgba(0, 0, 0, 0.1)',
      },
      bannerItem: {
        marginBottom: '2vw',
      },
      bannerTitle: {
        fontSize: '2vw',
        fontWeight: 'bold',
        color: '#3a5ba0',
        marginBottom: '1vw',
      },
      activityContainer: {
        display: 'flex',
        justifyContent: 'space-between',
      },
      activityBox: {
        width: '30%',
        backgroundColor: '#f1f1f1',
        borderRadius: '1vw',
        padding: '1vw',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        boxShadow: '0 0.5vw 1vw rgba(0, 0, 0, 0.1)',
      },
      activityImage: {
        width: '100%',
        height: '100%',
        borderRadius: '0.5vw',
      },
      activityName: {
        fontSize: '1.2vw',
        fontWeight: 'bold',
        color: '#3a5ba0',
        marginTop: '0.5vw',
      },
      calendarContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      calendarTile: {
        fontSize: '1vw',
      },
      selectedDateContainer: {
        marginTop: '2vw',
        width: '100%',
      },
      selectedDate: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        fontSize: '1.5vw',
        fontWeight: 'bold',
        color: '#3a5ba0',
        padding: '1vw',
        backgroundColor: '#ffffff',
        borderRadius: '0.5vw',
        boxShadow: '0 0.5vw 1vw rgba(0, 0, 0, 0.1)',
      },
      addIcon: {
        cursor: 'pointer',
        color: '#3a5ba0',
      },
      eventList: {
        marginTop: '1vw',
      },
      eventItem: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        padding: '1vw',
        borderRadius: '0.5vw',
        boxShadow: '0 0.5vw 1vw rgba(0, 0, 0, 0.1)',
        marginBottom: '1vw',
      },
      deleteIcon: {
        cursor: 'pointer',
        color: '#ff6347',
      },
      popupOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      },
      popup: {
        width: '30vw',
        backgroundColor: '#ffffff',
        color: '#3a5ba0',
        padding: '2vw',
        borderRadius: '1vw',
        boxShadow: '0 1vw 2vw rgba(0, 0, 0, 0.2)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      input: {
        width: '100%',
        padding: '1vw',
        fontSize: '1vw',
        marginBottom: '1vw',
        borderRadius: '0.5vw',
        border: '1px solid #ccc',
      },
      textarea: {
        width: '100%',
        padding: '1vw',
        fontSize: '1vw',
        marginBottom: '1vw',
        borderRadius: '0.5vw',
        border: '1px solid #ccc',
      },
      submitButton: {
        padding: '1vw 2vw',
        fontSize: '1vw',
        fontWeight: 'bold',
        color: '#ffffff',
        backgroundColor: '#3a5ba0',
        border: 'none',
        borderRadius: '0.5vw',
        cursor: 'pointer',
        marginBottom: '1vw',
      },
      cancelButton: {
        padding: '1vw 2vw',
        fontSize: '1vw',
        fontWeight: 'bold',
        color: '#ffffff',
        backgroundColor: '#ff6347',
        border: 'none',
        borderRadius: '0.5vw',
        cursor: 'pointer',
      },
    };
    
    export default styles;
    
  