const styles = {
  home: {
    minHeight: '100vh',
    fontFamily: "'Poppins', sans-serif",
    display: 'flex',
    backgroundColor: '#3a5ba0',
    color: 'white',
  },
  sidebar: {
    width: '120px',
    backgroundColor: '#ffffff',
    padding: '16px 8px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  content: {
    flex: 1,
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  banner: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '16px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    color: '#3a5ba0',
    width: '100%',
  },
  bannerItem: {
    marginBottom: '16px',
    color: '#3a5ba0',
  },
  bannerTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#3a5ba0',
    marginBottom: '8px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addActivityButton: {
    fontSize: '16px',
    padding: '4px 8px',
    backgroundColor: '#3a5ba0',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    marginLeft: '8px',
  },
  activityContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: '8px',
  },
  activityBox: {
    width: '28%',
    backgroundColor: '#f1f1f1',
    borderRadius: '12px',
    padding: '8px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    marginBottom: '8px',
  },
  activityImage: {
    width: '100%',
    height: '100%',
    borderRadius: '6px',
  },
  activityName: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#3a5ba0',
    marginTop: '4px',
  },
  popupOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popup: {
    width: '600px',
    backgroundColor: '#ffffff',
    color: '#3a5ba0',
    padding: '16px',
    borderRadius: '12px',
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  input: {
    width: '100%',
    padding: '12px',
    fontSize: '14px',
    marginBottom: '12px',
    borderRadius: '6px',
    border: '1px solid #ccc',
  },
  textarea: {
    width: '100%',
    padding: '12px',
    fontSize: '14px',
    marginBottom: '12px',
    borderRadius: '6px',
    border: '1px solid #ccc',
    minHeight: '80px',
  },
  popupButtonsContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: '12px',
  },
  submitButton: {
    padding: '6px 16px',
    backgroundColor: '#3a5ba0',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  cancelButton: {
    padding: '6px 16px',
    backgroundColor: '#ccc',
    color: '#333',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  activityPopup: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    maxWidth: '800px',
    maxHeight: '90vh',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
    overflow: 'hidden',
  },
  activityPopupImage: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  activityPopupImageStyle: {
    width: '100%',
    height: 'auto',
    objectFit: 'contain',
  },
  activityPopupContent: {
    flex: 1,
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    overflowY: 'auto',
  },
  activityTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    marginBottom: '8px',
    color: '#3a5ba0',
  },
  activityContent: {
    fontSize: '14px',
    marginBottom: '16px',
    color: '#3a5ba0',
  },
  closeButton: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#000',
    fontSize: '20px',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  commentsContainer: {
    flexGrow: 1,
    overflowY: 'auto',
    marginTop: '12px',
    marginBottom: '12px',
  },
  comment: {
    backgroundColor: '#f1f1f1',
    padding: '12px',
    borderRadius: '6px',
    marginBottom: '6px',
    fontSize: '14px',
    color: '#3a5ba0',
  },
  commentInputContainer: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '12px',
  },
  commentInput: {
    flexGrow: 1,
    padding: '12px 16px',
    fontSize: '14px',
    borderRadius: '6px',
    border: '1px solid #ccc',
    marginRight: '12px',
  },
  commentButton: {
    padding: '12px 16px',
    backgroundColor: '#3a5ba0',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
  },
};

export default styles;
