const styles = {
  home: {
    minHeight: '100vh',
    fontFamily: "'Poppins', sans-serif",
    display: 'flex',
    backgroundColor: '#3a5ba0',
    color: 'white',
  },
  sidebar: {
    width: '150px',
    backgroundColor: '#ffffff',
    padding: '2vw 1vw',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  content: {
    flex: 1,
    padding: '2vw',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  banner: {
    backgroundColor: '#ffffff',
    borderRadius: '1vw',
    padding: '2vw',
    boxShadow: '0 0.5vw 1vw rgba(0, 0, 0, 0.1)',
    color: '#3a5ba0',
    width: '100%',
  },
  bannerItem: {
    marginBottom: '2vw',
    color: '#3a5ba0',
  },
  bannerTitle: {
    fontSize: '2vw',
    fontWeight: 'bold',
    color: '#3a5ba0',
    marginBottom: '1vw',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addActivityButton: {
    fontSize: '2vw',
    padding: '0.5vw 1vw',
    backgroundColor: '#3a5ba0',
    color: 'white',
    border: 'none',
    borderRadius: '0.5vw',
    cursor: 'pointer',
    marginLeft: '1vw',
  },
  activityContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '1vw',
  },
  activityBox: {
    width: '30%',
    backgroundColor: '#f1f1f1',
    borderRadius: '1vw',
    padding: '1vw',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    boxShadow: '0 0.5vw 1vw rgba(0, 0, 0, 0.1)',
  },
  activityImage: {
    width: '100%',
    height: '100%',
    borderRadius: '0.5vw',
  },
  activityName: {
    fontSize: '1.2vw',
    fontWeight: 'bold',
    color: '#3a5ba0',
    marginTop: '0.5vw',
  },
  popupOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popup: {
    width: '50vw',
    backgroundColor: '#ffffff',
    color: '#3a5ba0',
    padding: '2vw',
    borderRadius: '1vw',
    boxShadow: '0 1vw 2vw rgba(0, 0, 0, 0.2)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  input: {
    width: '100%',
    padding: '1vw',
    fontSize: '1vw',
    marginBottom: '1vw',
    borderRadius: '0.5vw',
    border: '1px solid #ccc',
  },
  textarea: {
    width: '100%',
    padding: '1vw',
    fontSize: '1vw',
    marginBottom: '1vw',
    borderRadius: '0.5vw',
    border: '1px solid #ccc',
    minHeight: '8vw',
  },
  popupButtonsContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: '1vw',
  },
  submitButton: {
    padding: '0.5vw 2vw',
    backgroundColor: '#3a5ba0',
    color: 'white',
    border: 'none',
    borderRadius: '0.5vw',
    cursor: 'pointer',
    fontSize: '1vw',
  },
  cancelButton: {
    padding: '0.5vw 2vw',
    backgroundColor: '#ccc',
    color: '#333',
    border: 'none',
    borderRadius: '0.5vw',
    cursor: 'pointer',
    fontSize: '1vw',
  },
  activityPopup: {
    display: 'flex',
    width: '70vw',
    height: '70vh',
    backgroundColor: '#ffffff',
    borderRadius: '1vw',
    boxShadow: '0 1vw 2vw rgba(0, 0, 0, 0.2)',
    overflow: 'hidden',
  },
  activityPopupImage: {
    width: '50%',
    height: '100%',
  },
  activityPopupImageStyle: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: '1vw 0 0 1vw',
  },
  activityPopupContent: {
    width: '50%',
    padding: '2vw',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  commentsContainer: {
    flexGrow: 1,
    overflowY: 'auto',
    marginTop: '1vw',
    marginBottom: '1vw',
  },
  comment: {
    backgroundColor: '#f1f1f1',
    padding: '1vw',
    borderRadius: '0.5vw',
    marginBottom: '0.5vw',
    fontSize: '1vw',
    color: '#3a5ba0',
  },
  commentInputContainer: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '1vw',
  },
  commentInput: {
    flexGrow: 1,
    padding: '1vw',
    fontSize: '1vw',
    borderRadius: '0.5vw',
    border: '1px solid #ccc',
    marginRight: '1vw',
  },
  commentButton: {
    padding: '0.5vw 2vw',
    backgroundColor: '#3a5ba0',
    color: 'white',
    border: 'none',
    borderRadius: '0.5vw',
    cursor: 'pointer',
    fontSize: '1vw',
  },
  cancelButton: {
    padding: '0.5vw 2vw',
    backgroundColor: '#ccc',
    color: '#333',
    border: 'none',
    borderRadius: '0.5vw',
    cursor: 'pointer',
    fontSize: '1vw',
    alignSelf: 'flex-end',
    marginTop: '1vw',
  },
};

export default styles;